/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;
import Modelo.MatrizH;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../images/binary-code.png")).getImage());
        this.setResizable(false);
        this.setTitle("Buscador de Codigos lineales");
        this.setLocationRelativeTo(null);
    }
    public static MatrizH a=null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        d = new javax.swing.JSpinner();
        n = new javax.swing.JSpinner();
        k = new javax.swing.JSpinner();
        q = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(229, 229, 229));
        jLabel1.setText("D");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(229, 229, 229));
        jLabel2.setText("N");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(229, 229, 229));
        jLabel3.setText("K");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(229, 229, 229));
        jLabel4.setText("Q");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        jButton1.setBackground(new java.awt.Color(89, 89, 89));
        jButton1.setForeground(new java.awt.Color(229, 229, 229));
        jButton1.setText("Calcular");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 58, -1, -1));
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 17, 55, -1));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 17, 55, -1));
        getContentPane().add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 17, 56, -1));
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 59, 55, -1));

        jLabel7.setBackground(new java.awt.Color(76, 76, 76));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     *Captura los valores de la interface grafica y crea una MatrizH 
     *con la que trabajar, llama a Final.java de ser posible el calculo.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int qt=Integer.parseInt(q.getValue().toString());
        int nt=Integer.parseInt(n.getValue().toString());
        int kt=Integer.parseInt(k.getValue().toString());
        int dt=Integer.parseInt(d.getValue().toString());
        if(qt<=0 ||nt<=0 || kt<=0 || dt<=0){
            JOptionPane.showMessageDialog(null, "Todos los valores deben ser mayores que 0.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }else if (dt> nt-kt+1){
            JOptionPane.showMessageDialog(null, "D debe ser menor o igual a N-K+1.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }else if(!primo(qt)){
            JOptionPane.showMessageDialog(null, "Q debe ser primo", "ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            
        a = new MatrizH(nt,kt,qt,dt);
        //(n,k,q,d)
        //n-8,k-3,q-2,d-5
        //n=6,k=3,q=2,d=3
                if(a.MatrizL()!=null){
                    this.dispose();
                    Final vent =new Final();
                    vent.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna respuesta", "ERROR",JOptionPane.INFORMATION_MESSAGE);
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     *Verifica si un numero es primo
     * 
     *@param n numero a verificar
     * 
     * @return si es primo o no
     */
    private static boolean primo(int n){
           if(n==1)return false;
           if(n==2)return true;
           if(n%2!=0){
                int j = 3;
                int lim=(int)Math.sqrt(n);
                while (j <= lim) {
                    if (n%j==0) return false;
                    j+=2;
                }
            return true;
           }else return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner k;
    private javax.swing.JSpinner n;
    private javax.swing.JSpinner q;
    // End of variables declaration//GEN-END:variables
}
